# Generated by Django 5.1.15 on 2026-06-24 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_default_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=50)),
                ('token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'integration token',
                'verbose_name_plural': 'integration tokens',
                'db_table': 'accounts_integrationtoken',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
