# Generated by Django 5.1.15 on 2026-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_integrationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationtoken',
            name='token',
            field=models.CharField(max_length=512),
        ),
    ]
