# Generated by Django 5.1.15 on 2026-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_integrationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
