# Generated by Django 5.1.15 on 2026-06-24 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_branch', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('draft', 'Draft'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('number', models.IntegerField()),
                ('merge_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mrs', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_mrs', to=settings.AUTH_USER_MODEL)),
                ('closes_issues', models.ManyToManyField(blank=True, related_name='closing_mrs', to='issues.issue')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_mrs', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests', to='repositories.repository')),
            ],
            options={
                'db_table': 'merge_requests_mergerequest',
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MergeRequestComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mr_comments', to=settings.AUTH_USER_MODEL)),
                ('merge_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='merge_requests.mergerequest')),
            ],
            options={
                'db_table': 'merge_requests_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MergeRequestReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mr_reviews', to=settings.AUTH_USER_MODEL)),
                ('merge_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='merge_requests.mergerequest')),
            ],
            options={
                'db_table': 'merge_requests_review',
                'unique_together': {('merge_request', 'author')},
            },
        ),
    ]
