# Generated by Django 5.1.15 on 2026-07-16 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0003_codeownerrule_protectedbranch_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('time_of_day', models.TimeField(default='02:15')),
                ('enabled', models.BooleanField(default=True)),
                ('encrypt', models.BooleanField(default=True)),
                ('upload', models.BooleanField(default=True)),
                ('keep_local', models.PositiveIntegerField(default=14)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administration_backup_schedule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MirrorTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=1024)),
                ('enabled', models.BooleanField(default=True)),
                ('delete_remote_missing', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'administration_mirror_target',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administration_audit_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('create', 'Create'), ('verify', 'Verify'), ('restore', 'Restore'), ('test_restore', 'Test restore'), ('replicate', 'Replicate')], default='create', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('archive_path', models.CharField(blank=True, max_length=1024)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='administration.backupschedule')),
            ],
            options={
                'db_table': 'administration_backup_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('custom', 'Custom')], max_length=20)),
                ('source', models.CharField(max_length=1024)),
                ('target_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='repositories.repository')),
            ],
            options={
                'db_table': 'administration_repository_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('totp', 'TOTP'), ('webauthn', 'WebAuthn')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('secret', models.TextField(blank=True)),
                ('credential_id', models.CharField(blank=True, max_length=512)),
                ('public_key', models.TextField(blank=True)),
                ('sign_count', models.BigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administration_two_factor_device',
                'ordering': ['user__username', 'name'],
                'unique_together': {('user', 'method', 'name')},
            },
        ),
    ]
