# Generated by Django 5.1.15 on 2026-06-24 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(default='user', max_length=50)),
                ('owner_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal')], default='private', max_length=20)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_fork', models.BooleanField(default=False)),
                ('size_kb', models.BigIntegerField(default=0)),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='repositories.repository')),
            ],
            options={
                'db_table': 'repositories_repository',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'No access'), (10, 'Guest'), (20, 'Reporter'), (30, 'Developer'), (40, 'Maintainer'), (50, 'Owner')], default=30)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='repositories.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repositories_access',
                'unique_together': {('user', 'repository')},
            },
        ),
    ]
