# Generated by Django 5.1.15 on 2026-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='custom_disk_path',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
