# Generated by Django 5.1.15 on 2026-07-16 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_custom_disk_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOwnerRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=512)),
                ('raw_owners', models.CharField(blank=True, max_length=1024)),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_code_rules', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codeowner_rules', to='repositories.repository')),
            ],
            options={
                'db_table': 'repositories_codeowner_rule',
                'ordering': ['pattern'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedBranch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(default='main', max_length=255)),
                ('required_approvals', models.PositiveIntegerField(default=1)),
                ('allow_direct_push', models.BooleanField(default=False)),
                ('allow_force_push', models.BooleanField(default=False)),
                ('allow_delete', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_branches', to='repositories.repository')),
            ],
            options={
                'db_table': 'repositories_protected_branch',
                'ordering': ['pattern'],
                'unique_together': {('repository', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('changelog', models.TextField(blank=True)),
                ('is_prerelease', models.BooleanField(default=False)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_releases', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='repositories.repository')),
            ],
            options={
                'db_table': 'repositories_release',
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'tag_name')},
            },
        ),
    ]
