name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: "1.25"

      - name: Go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race ./...

      - name: Build binary
        run: go build -o mygit ./cmd/mygit

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        run: go build -o mygit.exe ./cmd/mygit

  docker:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Build Docker image
        run: docker build -t mygit:${{ github.sha }} .

      - name: Test Docker image
        run: |
          docker run -d -p 8060:8060 --name mygit --rm mygit:${{ github.sha }}
          sleep 5
          curl -f http://localhost:8060/ || exit 1
          docker stop mygit
